#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

class Event {
    public $functionClassName;
    public $payload;

    public function __construct($event)
    {
        foreach ($event as $key => $val) {
            $this->$key = $val;
        }
    }

    public function dispatch()
    {
        $functionClassName = $this->functionClassName;
        switch ($functionClassName) {
            case null:
            case 'dump':
                dump(collect($this)->toJson());
                break;
            default:
                $class = '\App\Functions\\'.$functionClassName;
                return (new $class)->handler($this->payload);
        }
    }
}

/**
 * lambda handler
 * 
 * @param object $event
 */
return function ($event) {
    return (new Event($event))->dispatch();
};
